# Generated by Django 4.2.19 on 2025-02-19 20:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('invapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemassociation',
            name='child_item',
        ),
        migrations.RemoveField(
            model_name='itemassociation',
            name='parent_item',
        ),
        migrations.AlterModelOptions(
            name='inventoryitem',
            options={'ordering': ['name'], 'verbose_name': 'Предмет инвентаря', 'verbose_name_plural': 'Предметы инвентаря'},
        ),
        migrations.AlterModelOptions(
            name='itemlocationassignment',
            options={'ordering': ['-assigned_at'], 'verbose_name': 'Распределение предмета', 'verbose_name_plural': 'Распределение предметов'},
        ),
        migrations.AlterModelOptions(
            name='itemtype',
            options={'ordering': ['name'], 'verbose_name': 'Тип предмета', 'verbose_name_plural': 'Типы предметов'},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['name'], 'verbose_name': 'Местоположение', 'verbose_name_plural': 'Местоположения'},
        ),
        migrations.RemoveField(
            model_name='itemlocationassignment',
            name='quantity',
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Стоимость'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='purchase_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата покупки'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='serial_number',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Серийный номер'),
        ),
        migrations.AddField(
            model_name='itemlocationassignment',
            name='assigned_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата размещения'),
        ),
        migrations.AddField(
            model_name='itemlocationassignment',
            name='removed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата удаления'),
        ),
        migrations.AddField(
            model_name='location',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='item_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='invapp.itemtype', verbose_name='Тип предмета'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название предмета'),
        ),
        migrations.AlterField(
            model_name='itemlocationassignment',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='invapp.inventoryitem', verbose_name='Предмет'),
        ),
        migrations.AlterField(
            model_name='itemlocationassignment',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='invapp.location', verbose_name='Местоположение'),
        ),
        migrations.AlterField(
            model_name='itemtype',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Название категории'),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Название местоположения'),
        ),
        migrations.AlterUniqueTogether(
            name='inventoryitem',
            unique_together={('name', 'serial_number')},
        ),
        migrations.AddConstraint(
            model_name='itemlocationassignment',
            constraint=models.UniqueConstraint(fields=('item', 'location'), name='unique_item_location'),
        ),
        migrations.DeleteModel(
            name='ItemAssociation',
        ),
    ]
