# Generated by Django 4.2.19 on 2025-02-25 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invapp', '0003_itemassociation'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='inventory_number',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Инвентарный номер'),
        ),
    ]
